---
- name: Sites Available
  copy:
    src: "sites-available/{{ item }}.conf"
    dest: /etc/apache2/sites-available
    owner: root
    group: root
    mode: 0644
    force: yes
  with_items:
    - gozma14.local
    - adminer.gozma14.local
    - www.gozma14.local

- name: Sites Enabled
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item }}.conf"
    state: link
  with_items:
    - gozma14.local
    - adminer.gozma14.local
    - www.gozma14.local
  notify:
    - apache2 | restart